# Generated by Django 3.2 on 2021-04-24 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantity_available', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('category', models.CharField(choices=[('SM', 'Supermarket'), ('HB', 'Health & Beauty'), ('HM', 'Home and Office'), ('PT', 'Phones & Tablet'), ('CM', 'Computing'), ('EL', 'Electronics'), ('FN', 'Fashion'), ('BP', 'Baby Products'), ('SG', 'SPorting goods'), ('AT', 'Automobile')], max_length=2)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
