# Generated by Django 3.2 on 2021-04-29 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='express_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='shipped_from_nigeria',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SM', 'Supermarket'), ('HB', 'Health & Beauty'), ('HM', 'Home and Office'), ('PT', 'Phones & Tablet'), ('CM', 'Computing'), ('EL', 'Electronics'), ('FN', 'Fashion'), ('FW', 'Foot Wear'), ('BP', 'Baby Products'), ('SG', 'SPorting goods'), ('AT', 'Automobile')], max_length=2),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.ManyToManyField(to='product.Rating'),
        ),
    ]
