# Generated by Django 3.2 on 2021-05-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210429_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SuperMarket', 'Supermarket'), ('Health & Beauty', 'Health & Beauty'), ('Home & Office', 'Home and Office'), ('Phones & Tablet', 'Phones & Tablet'), ('Computing', 'Computing'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('FootWear', 'Foot Wear'), ('Baby Products', 'Baby Products'), ('Sporting Goods', 'Sporting goods'), ('Automobile', 'Automobile')], max_length=40),
        ),
    ]
