# Generated by Django 3.2 on 2021-05-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210506_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
