# Generated by Django 3.2 on 2021-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rating_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, default='So it turns out this product s fairly awesome and i love how ti feels', max_length=1000),
            preserve_default=False,
        ),
    ]
