# Generated by Django 3.2 on 2021-05-08 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_favouriteproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriteproduct',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='favouriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
